import React from "react";
import {
  Typography,
  Button,
  Container,
  TextField,
  Radio,
  RadioGroup,
  FormControlLabel,
  FormControl,
  FormLabel,
  Toolbar,
} from "@mui/material";

import { makeStyles } from "@material-ui/core/styles";
import { useHistory } from "react-router-dom";

import "./Create.css";

import { nanoid } from "nanoid";
import format from "date-fns/format";

import { ref } from "../Firebasedb";

const useStyles = makeStyles({
  field: {
    marginTop: 20,
    marginBottom: 20,
    display: "block",
  },
  // btn:{
  //   fontSize: 20,
  //   backgroundColor: 'violet',
  //   '&:hover':{
  //     backgroundColor: 'blue'
  //   }
  // },
  // title:{
  //   textDecoration: 'underline',
  //   marginBottom: 20,
  // }
});

export default function Create() {
  const classes = useStyles();

  const history = useHistory();

  const [title, setTitle] = React.useState("");
  const [details, setDetails] = React.useState("");

  const [titleError, setTitleError] = React.useState(false);
  const [detailsError, setDetailsError] = React.useState(false);

  const [category, setCategory] = React.useState("Todo");

  const handleSubmit = (event) => {
    event.preventDefault();
    setTitleError(false);
    setDetailsError(false);

    if (title == "") {
      setTitleError(true);
    }
    if (details == "") {
      setDetailsError(true);
    }

    if (title && details) {
      const id = nanoid();
      const date = format(new Date(), "dd/MM/yyyy hh:mm bbb");

      // .doc() this uses the autogenerated id from firebase 
      ref
        .doc(id)
        .set({ id, title, details, category, date })
        .catch((err) => {
          alert(err);
          console.error(err);
        })
        .then(() => history.push("/"));
    }
  };

  return (
    <Container>
      <Typography
        className={classes.title}
        variant="h6"
        component="h2"
        // gutterBottom
        color="textSecondary"
      >
        CREATE A NOTE
      </Typography>

      <form noValidate autoComplete="off" onSubmit={handleSubmit}>
        <TextField
          // sx={{marginTop: 1}}
          margin="normal"
          // className={classes.field}
          className="field"
          onChange={(event) => setTitle(event.target.value)}
          label="Title"
          variant="outlined"
          // size="small"
          color="secondary"
          fullWidth
          required
          error={titleError}
        />

        <TextField
          // sx={{marginTop: 2, marginBottom: 2}}
          margin="normal"
          // className={classes.field}
          onChange={(event) => setDetails(event.target.value)}
          label="Description"
          variant="outlined"
          color="secondary"
          fullWidth
          required
          multiline
          rows={4}
          error={detailsError}
        />
        <Typography
        className={classes.title}
        variant="h6"
        component="h2"
          color="textSecondary"
          sx={{paddingTop: "8px" }}
      >
        CATEGORY:
      </Typography>

        <div sx={{paddingLeft: "0px" }}>
          <FormControl>
            {/* <FormLabel>Note Category</FormLabel> */}
            <RadioGroup
              value={category}
              onChange={(event) => setCategory(event.target.value)}
            >
              <FormControlLabel
                value="Event"
                control={<Radio color="secondary" />}
                label="Event"
              />
              <FormControlLabel
                value="Todo"
                control={<Radio color="secondary" />}
                label="Todo"
              />
              <FormControlLabel
                value="Remainder"
                control={<Radio color="secondary" />}
                label="Remainder"
              />
              <FormControlLabel
                value="Message"
                control={<Radio color="secondary" />}
                label="Message"
              />
            </RadioGroup>
          </FormControl>
        </div>

        <button>
          <div class="svg-wrapper-1">
            <div class="svg-wrapper">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z"></path>
                <path
                  fill="currentColor"
                  d="M1.946 9.315c-.522-.174-.527-.455.01-.634l19.087-6.362c.529-.176.832.12.684.638l-5.454 19.086c-.15.529-.455.547-.679.045L12 14l6-8-8 6-8.054-2.685z"
                ></path>
              </svg>
            </div>
          </div>
          <span>
            <strong>Create</strong>
          </span>
        </button>
      </form>
    </Container>
  );
}
